platform :ios, '9.0'
use_frameworks!

# Silent warnings from all pods
inhibit_all_warnings!

def common_pods
 pod 'MobileCore', :path => '../'
end

target 'MobileCoreExample' do
   common_pods
   pod 'SwiftLint'
   target 'MobileCoreExampleTests' do
        inherit! :search_paths
    end
end
