platform :ios, '10.0'
use_frameworks!

def common_pods
 pod 'MobileCore', :path => '../'
end

target 'MobileCoreExample' do
   common_pods
   pod 'SwiftLint'
end

target 'MobileCoreTests' do
  common_pods
end
