platform :ios, '9.0'
use_frameworks!

# Silent warnings from all pods
inhibit_all_warnings!

def common_pods
 pod 'MobileCore', :path => '../'
end

target 'FTMobileCore' do
   common_pods
   pod 'SwiftLint'
   target 'FTMobileCoreTests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Test'
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
            end
            if config.name == 'Debug'
              config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone', '-Xfrontend -warn-long-function-bodies=150', '-Xfrontend -warn-long-expression-type-checking=150']
              config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end
