name: Unit Testing

on:
  push:
    branches-ignore:
        - 'release/**'

jobs:
   swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run swiftlint
      run: bundle exec fastlane lint

   test:
    needs: swiftLint
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12 Pro Max']
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Unit Test
      run: bundle exec fastlane test
      env:
         destination: ${{ matrix.destination }}
    - name: Pod Lib Lint
      run: bundle exec fastlane podlibLint
    - name: Updload to codecov
      run: bash <(curl -s https://codecov.io/bash)
      
   documentation:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate Documentation
      uses: SwiftDocOrg/swift-doc@master
      with:
        inputs: "Sources"
        module-name: MobileCore
        output: "Documentation"
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "Documentation"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
