platform :ios, '9.0'
use_frameworks!

# Silent warnings from all pods
inhibit_all_warnings!

def local_path_source
    { :path => '../' }
end

def common_pods
 pod 'MobileCore', local_path_source
end

target 'FTMobileCoreSample' do
   common_pods
   target 'FTMobileCoreSampleTests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Test'
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
            end
        end
    end
end
